services:

  mariadb-post-service:
    image: mariadb:latest
    container_name: mariadb-post-service
    ports:
      - "3306:3306"
    volumes:
      - mariadb-post-service-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: PostServiceDB
      MYSQL_USER: user
      MYSQL_PASSWORD: password

  mariadb-comment-service:
    image: mariadb:latest
    container_name: mariadb-comment-service
    ports:
      - "3307:3306"
    volumes:
      - mariadb-comment-service-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: CommentServiceDB
      MYSQL_USER: user
      MYSQL_PASSWORD: password

  mariadb-review-service:
    image: mariadb:latest
    container_name: mariadb-review-service
    ports:
      - "3308:3306"
    volumes:
      - mariadb-review-service-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ReviewServiceDB
      MYSQL_USER: user
      MYSQL_PASSWORD: password

  rabbitmq:
    image: rabbitmq:latest
    container_name: rabbitmq
    ports:
      - "5672:5672"     # AMQP protocol port
      - "15672:15672"   # Management UI port
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

volumes:
  mariadb-post-service-data:
  mariadb-comment-service-data:
  mariadb-review-service-data:
  rabbitmq-data:
